project:
  type: website

website:
  title: "ISSS 608-January 2025, Group 7"
  navbar:
    left:
      - text: "Overview"
        menu:
        - text: "Proposal"
          href: Overview/Proposal.html
      - text: "Meeting Minutes"
        menu:
        - text: "Meeting Minutes 01"
          href: NOM/Meeting Minutes 01.html
        - text: "Meeting Minutes 02"
          href: NOM/Meeting Minutes 02.html
        - text: "Meeting Minutes 03"
          href: NOM/Meeting Minutes 03.html
      - text: "Shiny App"
        menu:
        - text: "Data Preparation"
          href: Shiny/Data_Prep.html
        - text: "Prototype"
          href: Shiny/Prototype.html
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

