project:
  type: website

website:
  title: "WeatherWatch SG"
  
  navbar:
    left:
      - text: "Overview"
        href: Proposal.html
      - text: "Shiny App"
        menu:
        - text: "Data Preparation"
          href: Shiny/Data_Prep.html
        - text: "Prototype"
          href: Shiny/Prototype.html
      - Team.qmd
      - text: "Meeting Minutes"
        menu:
        - text: "Meeting Minutes 01"
          href: NOM/Meeting Minutes 01.html
        - text: "Meeting Minutes 02"
          href: NOM/Meeting Minutes 02.html
        - text: "Meeting Minutes 03"
          href: NOM/Meeting Minutes 03.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

