project:
  type: website

website:
  title: "<img src='icon.png' style='height:40px;'>"
  
  navbar:
    left:
      - text: "Poster"
        href: Poster.html
      - text: "Prototypes"
        menu:
        - text: "General Data Preparation"
          href: Shiny/Data_Prep.html
        - text: "EDA & CDA"
          href: Prototypes/Eda.html
        - text: "Time Series Forecasting"
          href: Prototypes/Time.html
        - text: "Geospatial Analysis"
          href: Prototypes/Geo.html
      - text: "Shiny App"
        href: Shiny/Prototype.html
      - text: "Team"
        menu:
        - Team.qmd
        - text: "Meeting Minutes 01"
          href: NOM/Meeting Minutes 01.html
        - text: "Meeting Minutes 02"
          href: NOM/Meeting Minutes 02.html
        - text: "Meeting Minutes 03"
          href: NOM/Meeting Minutes 03.html
        - text: "Meeting Minutes 04"
          href: NOM/Meeting Minutes 04.html
        - text: "Meeting Minutes 05"
          href: NOM/Meeting Minutes 05.html
        - text: "Meeting Minutes 06"
          href: NOM/Meeting Minutes 06.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

